baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Hugo-Static'
theme = 'lugo'

[outputs]
home = ["HTML", "JSON"]

[params]

  #list items
  datesinlist = true
  authorsinlist = true

  #footer items
  nextprev = true
  taglist = true
  showrss = true
